### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by d7e7r7** [blackeko/yesitsme#1]
I got this error message: 

Traceback (most recent call last):
  File "C:\Users\David\yesitsme\yesitsme.py", line 244, in <module>
    main()
  File "C:\Users\David\yesitsme\yesitsme.py", line 143, in main
    if(infos["full_name"].lower() == name.lower()):
KeyError: 'full_name'

**Comment by FranciscoRobbins75** [comment]
i got the same issue :(

**Comment by 2thecurve** [comment]
Same issue
