### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by traceback-afk** [blackeko/yesitsme#12]
C:\Users\npc\Documents\workspace\osint_yesitsme\yesitsme.py:21: SyntaxWarning: invalid escape sequence '\/'
  print(" | || / -_|_-< | |  _|/(_-< | '  \/ -_)")
C:\Users\npc\Documents\workspace\osint_yesitsme\yesitsme.py:22: SyntaxWarning: invalid escape sequence '\_'
  print("  \_, \___/__/ |_|\__| /__/ |_|_|_\___|")
Traceback (most recent call last):
  File "C:\Users\npc\Documents\workspace\osint_yesitsme\yesitsme.py", line 10, in <module>
    import requests
  File "C:\Users\npc\Documents\workspace\osint_yesitsme\env\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\npc\Documents\workspace\osint_yesitsme\env\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\npc\Documents\workspace\osint_yesitsme\env\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\npc\Documents\workspace\osint_yesitsme\env\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

**Comment by mehdifirefox** [comment]
Sorry, I don't open a new topic.

I installed Python, but it gives an error, Python is not installed

**Comment by Shumaila2** [comment]
> C:\Users\npc\Documents\workspace\osint_yesitsme\yesitsme.py:21: SyntaxWarning: invalid escape sequence '/'
> print(" | || / -_|_-< | | _|/(_-< | ' / -_)") C:\Users\npc\Documents\workspace\osint_yesitsme\yesitsme.py:22: SyntaxWarning: invalid escape sequence '_' print(" _, _**/**/ |_|__| /__/ |_|_|____|") Traceback (most recent call last): File "C:\Users\npc\Documents\workspace\osint_yesitsme\yesitsme.py", line 10, in import requests File "C:\Users\npc\Documents\workspace\osint_yesitsme\env\Lib\site-packages\requests__init__.py", line 43, in import urllib3 File "C:\Users\npc\Documents\workspace\osint_yesitsme\env\Lib\site-packages\urllib3__init__.py", line 7, in
> from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
> File "C:\Users\npc\Documents\workspace\osint_yesitsme\env\Lib\site-packages\urllib3\connectionpool.py", line 11, in
> from .exceptions import (
> File "C:\Users\npc\Documents\workspace\osint_yesitsme\env\Lib\site-packages\urllib3\exceptions.py", line 2, in
> from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
> ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

run this in your virtual env:
pip install urllib3==1.26.18
